name: Push Updates

on:
  workflow_dispatch:

jobs:
  bake:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Get Versions
        id: script
        run: python3 dev/baker.py

    outputs:
      matrixes: ${{ steps.script.outputs.matrixes }}

  build:
    needs: bake
    strategy:
      matrix: ${{ fromJSON(needs.bake.outputs.matrixes).builder }}

    permissions:
      contents: read
      packages: write

    uses: NathanVaughn/reusable-actions/.github/workflows/docker-build-push.yml@main
    with:
      platform: linux/amd64
      tags: ${{ matrix.tags }}
      context: docker
      dockerfile: docker/${{ matrix.dockerfile }}
      attest_id: ${{ matrix.attest_id }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  attest:
    needs:
      - bake
      - build
    strategy:
      matrix: ${{ fromJSON(needs.bake.outputs.matrixes).attester }}

    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write

    uses: NathanVaughn/reusable-actions/.github/workflows/docker-attest.yml@main
    with:
      name: ${{ matrix.name }}
      attest_id: ${{ matrix.attest_id }}
    # secrets:
    #   dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
    #   dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  update-dockerhub:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Update DockerHub README
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          destination_container_repo: ${{ secrets.DOCKERHUB_USERNAME }}/powerpanel-business
          provider: dockerhub
          short_description: ${{ github.event.repository.description }}
